# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 760cee7a15f6b5b71a0f155eef8704e512cc5548442c58af0b7d8e8d93f92d4a3d75c4d4a348c8151891847ebf2fddab405b05e9e4d3d959178310d7f38ae556

test:
  secret_key_base: 1e03020bdaf9a1877fe42bed3773f034d2ac059ef8611939dbf583b77ec9db96e6ef5b240614f83f6a92051af1abfb17b6b353f68e41b731bf98f24259f3a5f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
