# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf6169aa417a926ee6331638b6309b37b05fb5ef0449eefb73799cf3136d8a0089b1bce71ab3ac5754a4dc75884456af9ac53d1fe8c44857cd56136395bf2923

test:
  secret_key_base: a3d4aa78601252c273902ed0da60e15349a3365aaeaff68e37b60d7fd347df0cc6e9b9967dec93e04e39460ad46da1948aefaf686ffdd14a9d31960cb6263ee6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
